#!/bin/bash

#SBATCH -N 1
#SBATCH --exclusive
#SBATCH --partition=Blade
#SBATCH --nodelist=nodo1
#SBATCH -o salidaByFunction.txt
#SBATCH -e erroresByFunction.txt

echo "Algoritmo a ejecutar"
time ./4x a
