#!/bin/bash

#SBATCH -N 1
#SBATCH --exclusive
#SBATCH --partition=Blade
#SBATCH --nodelist=nodo16
#SBATCH -o salidaInicial.txt
#SBATCH -e erroresInicial.txt

echo Iniciando el programa cambiando nodo a 16
time ./vieja
echo Fin del programa
